
quicket_productid: 34636

waiting_list_url: https://docs.google.com/forms/u/2/d/e/1FAIpQLSewoGGAeOHqaM_s874fuah49QUEkbjFh8OBNXqPDlis0qVWuw/viewform

current_year: 2019

years:
  - 2019
  - 2018
  - 2017
  - 2016
  - 2015
  - 2014
  - 2013
  - 2012

dates: 7 & 8 March 2019

homepage_sections:
  upcoming_conference: false
  tickets_sell: true
  tickets_soldout: false
  tickets_waitinglist: false
  tickets_notify: true
  current_speakers: false
  previous_speakers: true
  sponsors: true
navigation:
  submit: false
  schedule: false
