
quicket_productid: 34637

waiting_list_url: https://docs.google.com/forms/d/1WOB3UD0XMfljzwqoqvqIw36xnuDbPs0RcjZDG5_L_4o/viewform

current_year: 2018

years:
  - 2018
  - 2017
  - 2016
  - 2015
  - 2014
  - 2013

dates: 8-9 March 2018

homepage_sections:
  upcoming_conference: false
  tickets_sell: false
  tickets_soldout: true
  tickets_waitinglist: true
  tickets_notify: false
  current_speakers: true
  previous_speakers: false
  sponsors: true
navigation:
  submit: false
  schedule: false
