
quicket_productid: 34636

waiting_list_url: https://docs.google.com/forms/d/e/1FAIpQLSewoGGAeOHqaM_s874fuah49QUEkbjFh8OBNXqPDlis0qVWuw/viewform?usp=sf_link

current_year: 2020

years:
  - 2020
  - 2019
  - 2018
  - 2017
  - 2016
  - 2015
  - 2014
  - 2013
  - 2012

dates: 5 & 6 March 2020

homepage_sections:
  upcoming_conference: false
  tickets_sell: false
  tickets_soldout: false
  tickets_waitinglist: false
  tickets_notify: true
  current_speakers: false
  previous_speakers: true
  sponsors: true
navigation:
  submit: true
  schedule: false
