
quicket_productid: 34637

waiting_list_url: https://docs.google.com/forms/d/1WOB3UD0XMfljzwqoqvqIw36xnuDbPs0RcjZDG5_L_4o/viewform

current_year: 2018

years:
  - 2018
  - 2017
  - 2016
  - 2015
  - 2014
  - 2013

dates: 2019 dates to be confirmed

homepage_sections:
  upcoming_conference: false
  tickets_sell: false
  tickets_soldout: false
  tickets_waitinglist: false
  tickets_notify: true
  current_speakers: false
  previous_speakers: true
  sponsors: true
navigation:
  submit: false
  schedule: false
