
quicket_productid: 34637

waiting_list_url: https://docs.google.com/forms/d/1WOB3UD0XMfljzwqoqvqIw36xnuDbPs0RcjZDG5_L_4o/viewform

current_year: 2019

years:
  - 2019
  - 2018
  - 2017
  - 2016
  - 2015
  - 2014
  - 2013
  - 2012

dates: 7 & 8 March 2019

homepage_sections:
  upcoming_conference: true
  tickets_sell: false
  tickets_soldout: false
  tickets_waitinglist: false
  tickets_notify: true
  current_speakers: false
  previous_speakers: true
  sponsors: true
navigation:
  submit: true
  schedule: false
